---
title: "Merging Censoc and IPUMS datasets"
output: html_notebook
---

It is straightforward to match CENSOC data to IPUMS census data once both datasets have been [obtained](https://censoc.demog.berkeley.edu/articles/ipums_document.html).  

The variable "HISTID" uniquely identifies  all records for both Censoc and the full count census and can be used to match records between the two datasets. 

A tidyverse join: 
```{r}
library(tidyverse)

censoc <- read_csv('path/to/your/censoc')
census <- read_csv('path/to/your/census')

merged_df <- censoc %>%
  left_join(census, by = "HISTID")
```

A data.table merge (probably faster): 
```{r}
library(data.table)

censoc <- fread('path/to/your/censoc', nrows=7564451)
census <- fread('/90days/casey/ipums_1940_full_count.csv', nrows = 7564451)

setkey(censoc, HISTID)
setkey(census, HISTID)

merged_df <- censoc[census, nomatch=0]
```

RAM-saving approach using the IPUMSR Package: 
```{r}
library(ipumsr)
library(tidyverse)

censoc <- read_csv('/90days/casey/censoc_false_histid.csv')

read_ipums_micro_chunked("/path/to/census/data" , ddi = "path/to/ddi", chunk = 10000, callback = cb)


cb_function <- function(x, pos) {
 right_join(censoc, by = "HISTID")
}

cb <- IpumsDataFrameCallback$new(cb_function)

```

